### PR TITLE
fix(BED-6314): fix --jwt code path

### LINKED ISSUE #122: Error "failed to create new Azure client: unable to authenticate. no valid credential provided" when authenticating using a JWT in Azurehound later than 2.2.1
Hi,

Using Azurehound 2.3.1 or 2.3.0 and authenticating using a JWT errors with "failed to create new Azure client: unable to authenticate. no valid credential provided". This errors in both Kali and Windows 11.

Using Azurehound 2.2.1 and authenticating using the same JWT as above, works.

The command I use in both cases is `./azurehound -j "[JWT]" list -o output.json`

I also noticed that while the output from 2.2.1 can be ingested into Bloodhound CE 7.0.1, none of the built-in Azure queries actually find anything... The file output.json does have what looks like legit data in it...

Thanks for looking into this!

### PR DESCRIPTION
**Pull request by benwaples**
This PR addresses a bug preventing the use of JWT authentication for AzureHound. 

During a refactor introducing `AuthStrategy` (which is great) there was a small change in the code flow that no longer checked for a JWT before attempting to refresh authentication, causing an error during said auth refresh because there wouldn't be any other valid creds.

closes: #122

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevents unnecessary token refresh attempts when a valid JWT is provided, reducing latency and potential authentication errors.

### CODE REVIEW

**Comment by benwaples** [comment]
@coderabbitai review

File: client/rest/auth.go [hunk 1]
```diff
@@ -145,9 +146,14 @@ func NewGenericAuthenticator(config config.Config, auth *url.URL, api *url.URL)
...
 // Authenticate if needed and add authentication to the request
 func (s *Authenticator) AddAuthenticationToRequest(restClient *restClient, req *http.Request) (*http.Request, error) {
-	if err := s.refreshIfExpired(restClient); err != nil {
-		return nil, err
+
+	// Don't refresh auth if a JWT is provided via config
+	if !s.auth.isJWTProvided() {
+		if err := s.refreshIfExpired(restClient); err != nil {
+			return nil, err
+		}
```
Comment (benwaples) [inline client/rest/auth.go:154]: This is the fix -- only attempt refreshing auth if a jwt was not provided.

**Review by ddlees — APPROVED** [review]
